# -*- coding: utf-8 -*-
"""TensorFlowNeuralNetwork

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18EEMUA00kphxYjfXkrE0ycNsXXCD4-lW

# Basic TensorFlow Neural Network

The code below uses the MNIST dataset already on TensorFlow and trains with it with a neural network. The neural network has five layers.

1.   A layer to flatten the 28x28 images into 784 input neurons
2.   A dense layer (in which all neurons are connected) of 512 neurons which uses a ReLU activation function
3.   Another dense layer of 512 neurons which uses a ReLU activation function
4.   A dropout layer which does ...
5.   A final layer with 10 outputs for each of the numbers. This uses a softmax activation function

The network trains with 60000 MNIST digits from the data set, for 5 epochs, and then evaluates with the other 10000. An epoch is a measure of the number of times all of the training vectors are used once to update the weights.
For batch training, this nn, all of the training samples pass through the neural network simultaneously in one epoch before weights are updated.

The two values at the end are metrics we can use to evaluate the network, the **loss** and **accuracy**. A loss function optimizes the network by producing the optimum weights. The loss value shows the inconsistency between the predicted value and the actual label. Whereas accuracy measures performance in an interpretable manner, by showing the percentage of correctly predicted outputs.
"""

import tensorflow as tf
mnist = tf.keras.datasets.mnist

(x_train, y_train),(x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(512, activation=tf.nn.relu),
  tf.keras.layers.Dense(512, activation=tf.nn.relu),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10, activation=tf.nn.softmax)
])
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

model.fit(x_train, y_train, epochs=5)
model.evaluate(x_test, y_test)